version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo installing sam 
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo installing npm packages
      - cd hello-world &&  npm install && cd ..
  build:
    commands:
      - echo build environment is `date`
      - echo build started at $ENV_NAME
      - echo build started at $ZIPMONEY_API
      - echo deploying with sam
      - echo assume role to execute
      - aws cloudformation package --template-file template.yaml --s3-bucket janahitha-lambda --output-template-file sam-template.yaml
      #- aws cloudformation deploy --template-file sam-template.yaml --stack-name sam-stack-$ENV_NAME --capabilities CAPABILITY_IAM --parameter-overrides Environment=$ENV_NAME ZipApiKey=$ZIPMONEY_API
  post_build:
    commands:
      - echo deployment completed at `date`

artifacts:
  type: zip
  files:
    - template.yaml
    - sam-template.yaml

