AWSTemplateFormatVersion: '2010-09-09'
Description: Chat Pre Stack

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.80.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Join [ '-', [ 'proxy-vpc' , !Ref Environment ] ]

Outputs:
  myVPC:
    Description: sub stack VPC 
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

#aws cloudformation create-stack --stack-name proxy-main --parameter-overrides Environment=dev --profile home