AWSTemplateFormatVersion: '2010-09-09'
Description: Chat Pre Stack

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.80.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Join [ '-', [ 'proxy-vpc' , !Ref Environment ] ]

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-east-1a
      CidrBlock: 10.80.32.0/19
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: payment-proxy-public-subnet

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: payment-proxy-lambda-sg
      GroupDescription: payment-proxy-lambda-sg
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: payment-proxy-lambda-sg

Outputs:
  myVPC:
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

  mySubNet:
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-SUBNET"

  mySecGroup:
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-SECGROUP"

#aws cloudformation create-stack --stack-name proxy-main --parameter-overrides Environment=dev --profile home