AWSTemplateFormatVersion: '2010-09-09'
Description: Sample SAM Template for sam-app
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: s3://janahitha-lambda/5864573c15ea6df4ea3bdc686f841f4a
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /hello
          Type: Api
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
