AWSTemplateFormatVersion: '2010-09-09'
Description: Proxy VPC
# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.80.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Join [ '-', [ 'payment-proxy-vpc' , !Ref Environment ] ]

# Outputs:
#   myVPC:
#     Description: sub stack VPC 
#     Value: !Ref VPC
#     Export:
#       Name: my-vpc-id

Outputs:
  Value:
    Ref: VPC
  Export:
    Name: my-vpc-id