AWSTemplateFormatVersion: '2010-09-09'
Description: Proxy VPC

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.80.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Join [ '-', [ 'payment-proxy-vpc' , !Ref Environment ] ]

Outputs:
  myVPC:
    Description: sub stack VPC 
    Value: janaBoy
    Export:
      Name: expMyVpc

  # VpcId:
  #   Value: !Ref VPC
  #   Export:
  #     Name: Unique-VpcId