AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sam-app
  
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        ENV_NAME: !Ref Environment
        API_KEY: !Ref ZipApiKey
        REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments

  ZipApiKey:
    Type: String
    Default: ''
    Description: ZipMoney Api Key

Mappings:
  EnvMappings:
    dev:
      region: eu-west-1
      url: payment-proxy.dev.travcorpservices.com
    qa:
      region: eu-west-1
      url: payment-proxy.qa.travcorpservices.com
    uat:
      region: eu-west-1
      url: payment-proxy.uat.travcorpservices.com
    prod:
      region: eu-west-1
      url: payment-proxy.travcorpservices.com

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      FunctionName: !Join [ '-', [ 'HelloBuddy' , !Ref Environment ] ]
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          ENV_NAME: !Ref Environment
          API_KEY: !Ref ZipApiKey
          REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]