AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sam-app test with gitFlow and set develop v3
  
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        ENV_NAME: !Ref Environment
        API_KEY: !Ref ZipApiKey
        REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

  ZipApiKey:
    Type: String
    Default: ''
    Description: ZipMoney Api Key

Mappings:
  EnvMappings:
    dev:
      region: eu-west-1
    qa:
      region: eu-west-1
    uat:
      region: eu-west-1
    prod:
      region: eu-west-1

Resources:
  Proxy-Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://janahitha-lambda-dev.s3.amazonaws.com/sub-template.yaml
      TimeoutInMinutes: 2

  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      FunctionName: !Join [ '-', [ 'payment-test-chat' , !Ref Environment ] ]
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          ENV_NAME: !Ref Environment
          API_KEY: !Ref ZipApiKey
          REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]