AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proxy Import
  
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        ENV_NAME: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "pre-stack-VPCID"
      AvailabilityZone: eu-east-1a
      CidrBlock: 10.80.32.0/19
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: payment-proxy-public-subnet
       
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      FunctionName: my-lambda-import-xyz
      #FunctionName: !Join [ '-', [ 'payment-test-chat' , Fn::ImportValue: expMyVpc] ]
      #FunctionName: Fn::ImportValue: !Sub "sub-VPCID"
      # FunctionName:
      #   Fn::ImportValue:
      #     Fn::Sub: 'sub-VPCID'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          ENV_NAME: !Ref Environment
          #REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]