AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proxy Import
  
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        ENV_NAME: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Application development environments for sam.

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      #FunctionName: !Join [ '-', [ 'payment-test-chat' , Fn::ImportValue: expMyVpc] ]
      #FunctionName: Fn::ImportValue: !Sub "sub-VPCID"
      FunctionName: Hello-world-July
        #  Fn::ImportValue:
        #    Fn::Sub: 'pre-stack-VPCID'
      VpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue:
             Fn::Sub: 'pre-stack-SECGROUP'
        SubnetIds: 
          - Fn::ImportValue:
             Fn::Sub: 'pre-stack-SUBNET'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          ENV_NAME: !Ref Environment
          #REGION: !FindInMap [ EnvMappings, !Ref Environment, region ]